spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database
    driverClassName: org.h2.Driver

server:
  port: 8080

logging:
  level:
    org.springframework:
      jdbc: DEBUG
